# Changes here will be overwritten by Copier
_commit: v1
_src_path: git+https://github.com/WaylonWalker/markata-blog-starter
author_email: vimconf2022@pype.dev
author_fullname: Nicholas Payne
author_twitter: '@pypeaday'
description: VimConf 2022 material
project_name: Vim Conf 2022
python_package_import_name: vim_conf_2022
url: https://pypeaday.github.io/vimconf-2022

